single_class:
  parent_directory: "ShapeNet_data"
  output_base_dir: "single_class/data/data"
  data_folder: "single_class/data"
  trained_models_dir: "single_class/trained_models"
  plots_dir: "single_class/plots"

  shapes:
    - "cars"

  max_objects_per_type: 2

  latent_dim: 64
  hidden_dim: 512
  num_layers: 16
  batch_size_train: 512
  batch_size_val: 32
  lr_decoder: 0.0001
  lr_latent: 0.001
  latent_reg_weight: 0.0001
  num_epochs: 2

  grid_size: 500
  grid_range: [-448, 448]
  num_iterations: 100
  lr_visualization: 0.1

multi_class:
  parent_directory: "ShapeNet_data"
  output_base_dir: "multi_class/data/data"
  data_folder: "multi_class/data"
  trained_models_dir: "multi_class/trained_models"
  plots_dir: "multi_class/plots"

  shapes:
    - "airplanes"
    - "cars"
    - "train"

  max_objects_per_type: 150

  latent_dim: 64
  hidden_dim: 512
  num_layers: 16
  batch_size_train: 512
  batch_size_val: 32
  lr_decoder: 0.0001
  lr_latent: 0.001
  latent_reg_weight: 0.0001
  num_epochs: 100

  grid_size: 500
  grid_range: [-448, 448]
  num_iterations: 5000
  lr_visualization: 0.1
