single_class:
  parent_directory: "ShapeNet_data"
  output_base_dir: "single_class/data/data"
  data_folder: "single_class/data"
  trained_models_dir: "single_class/trained_models"
  plots_dir: "single_class/plots"

  grid_size: 500
  grid_range: [ -448, 448 ]
  num_iterations: 100
  lr_visualization: 0.1

  shapes:
    - "cars"

  max_objects_per_type: 2

multi_class:
  parent_directory: "ShapeNet_data"
  output_base_dir: "multi_class/data/data"
  data_folder: "multi_class/data"
  trained_models_dir: "multi_class/trained_models"
  plots_dir: "multi_class/plots"

  grid_size: 500
  grid_range: [ -448, 448 ]
  num_iterations: 100
  lr_visualization: 0.1

  shapes:
    - "airplanes"
    - "cars"
    - "trains"

  max_objects_per_type: 150